# Generated by Django 2.0.6 on 2018-06-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_todoentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
